name: Deploy to Railway Project

on:
  push:
    branches: [production_v1]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 18x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Load Environment Variables
        run: |
          if [ "$GITHUB_EVENT_NAME" == "push" ] && [ "$GITHUB_REF" == "refs/heads/production_v1" ]; then
            echo "Loading production environment variables..."
            cp .env.production .env
          else
            echo "Loading default environment variables..."
            cp .env.development .env
          fi

      - name: Install packages
        run: npm install

      - name: Install prisma
        run: npm run generate

      - name: Load env
        run: npm run env:prod

      - name: Run tests
        run: npm test

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy to Railway

        run: railway list
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
