name: Deploy to Railway Project

on:
  push:
    branches: [production_v1]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 18x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install packages
        run: npm install

      - name: Run tests
        run: npm test

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
