name: Deploy to Zeet

on:
  push:
    branches:
      - development_auth_server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      #   - name: Login to Docker
      #     uses: docker/login-action@v3
      #     with:
      #       username: khanhvo9484
      #       password: ${{ secrets.DOCKER_HUB_TOKEN }}
      #   - name: Build Docker Image
      #     run: docker build -t khanhvo9484/development_auth_server:latest .
      #   - name: Push Docker Image
      #     run: docker push khanhvo9484/development_auth_server:latest
      - name: Deploy project
        uses: zeet-co/zeet-deploy-action@v2
        with:
          deploy_key: ${{ secrets.ZEET_API_TOKEN }}
          project: zeet-k3/development_auth_server
        #   image: khanhvo9484/development_auth_serverd
